import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'goBackHome': 'Return to Home',
'home.genderLabel': 'Gender',
'Gender.Male': 'Male',
'home.ageLabel': 'Age',
'event': 'Add Event',     
'auth.sexFormField': 'Sex',
'auth.ageFormField': 'Age',
'auth.signInButton': 'Sign In',
'auth.signUpButton': 'Sign Up',
'auth.resetPasswordButton': 'Send Password Reset',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Password',
'auth.nameFormField': 'Name',
'auth.signInErrorTitle': 'Sign In Error',
'auth.signInError': 'Login failed: email or password incorrect.',
'auth.resetPasswordLabelButton': 'Forgot password?',
'auth.signUpLabelButton': 'Create an Account',
'auth.signUpErrorTitle': 'Sign Up Failed.',
'auth.signUpError': 'There was a problem signing up.  Please try again later.',
'auth.signInLabelButton': 'Have an Account? Sign In.',
'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
'auth.resetPasswordFailed': 'Password Reset Email Failed',
'auth.signInonResetPasswordLabelButton': 'Sign In',
'auth.updateUser': 'Update Profile',
'auth.updateUserSuccessNoticeTitle': 'User Updated',
'auth.updateUserSuccessNotice': 'User information successfully updated.',
'auth.updateUserEmailInUse': 'That email address already has an account.',
'auth.updateUserFailNotice': 'Failed to update user',
'auth.enterPassword': 'Enter your password',
'auth.cancel': 'Cancel',
'auth.submit': 'Submit',
'auth.changePasswordLabelButton': 'Change Password',
'auth.resetPasswordTitle': 'Reset Password',
'auth.updateProfileTitle': 'Update Profile',
'auth.wrongPasswordNoticeTitle': 'Login Failed',
'auth.wrongPasswordNotice': 'The password does not match our records.',
'auth.unknownError': 'Unknown Error',
'settings.title': 'Settings',
'settings.language': 'Language',
'settings.theme': 'Theme',
'settings.signOut': 'Sign Out',
'settings.dark': 'Dark',
'settings.light': 'Light',
'settings.system': 'System',
'settings.updateProfile': 'Update Profile',
'home.title': 'Home',
'home.nameLabel': 'Name',
'home.uidLabel': 'UID',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin User',
'app.title': 'Flutter Starter Project',
'validator.email': 'Please enter a valid email address.',
'validator.password': 'Password must be at least 6 characters.',
'validator.name': 'Please enter a name.',
'validator.number': 'Please enter a number.',
'validator.notEmpty': 'This is a required field.',
'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
},
    'ro': {
'event': 'Adaugă eveniment',
'auth.sexFormField': 'Gen',
'auth.ageFormField': 'Vârstă',
'auth.signInButton': 'Logare',
'auth.signUpButton': 'Înregistrare',
'auth.resetPasswordButton': 'Resetare parolă',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Parolă',
'auth.nameFormField': 'Nume',
'auth.signInErrorTitle': 'Eroare la înregistrare',
'auth.signInError': 'Logare eșuată: email sau parolă greșită',
'auth.resetPasswordLabelButton': 'Ai uitat parola?',
'auth.signUpLabelButton': 'Crează cont',
'auth.signUpErrorTitle': 'Înregistrare eșuată',
'auth.signUpError': 'A apărut o problemă la înregistare. Revino mai târziu.',
'auth.signInLabelButton': 'Ai deja cont? Loghează-te',
'auth.resetPasswordNoticeTitle': 'A fost trimis email-ul pentru resetarea parolei.',
'auth.resetPasswordNotice': 'Verifică email-ul și urmărește instrucțiunile pentru a-ți reseta parola',
'auth.resetPasswordFailed': 'Resetarea parolei a eșuat',
'auth.signInonResetPasswordLabelButton': 'Loghează-te',
'auth.updateUser': 'Actualizează profilul',
'auth.updateUserSuccessNoticeTitle': 'Utilizator actualizat',
'auth.updateUserSuccessNotice': 'Informațiile utilizatorului au fost actualizate cu succes.',
'auth.updateUserEmailInUse': 'Exista deja un cont cu această adresa de email',
'auth.updateUserFailNotice': 'Actualizarea utilizatorului a eșuat',
'auth.enterPassword': 'Introduceți parola',
'auth.cancel': 'Anulează',
'auth.submit': 'Trimite',
'auth.changePasswordLabelButton': 'Schimbă parola',
'auth.resetPasswordTitle': 'Resetează parola',
'auth.updateProfileTitle': 'Actualizează profilul',
'auth.wrongPasswordNoticeTitle': 'Logare eșuată',
'auth.wrongPasswordNotice': 'Parolă greșită',
'auth.unknownError': 'Eroare necunoscută',
'settings.title': 'Setări',
'settings.language': 'Limbă',
'settings.theme': 'Temă',
'settings.signOut': 'Delogare',
'settings.dark': 'Noapte',
'settings.light': 'Zi',
'settings.system': 'Sistem',
'settings.updateProfile': 'Actualizează profilul',
'home.title': 'Acasă',
'home.nameLabel': 'Nume',
'home.uidLabel': 'UID',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Administrator',
'app.title': 'Flutter Starter Project',
'validator.email': 'Introduceți o adresă de email validă',
'validator.password': 'Parola trebuie sa aibă minim 6 caractere',
'validator.name': 'Introduceți un nume',
'validator.number': 'Introduceți un număr',
'validator.notEmpty': 'Acest câmp este obligatoriu',
'validator.amount': 'Vă rugăm alegeți un număr, de ex: 250 fără alte caractere',
},


        };
      }
      